version: '3.8'
services:
  prometheus-bot:
    image: sleaxdyy/telegram-bot:latest
    volumes:
      - ./telegram-bot/:/etc/telegrambot/
      - ./telegram-bot/config.yaml:/config.yaml
      - ./telegram-bot/template.tmpl:/template.tmpl
    container_name: prometheus-bot
    restart: unless-stopped
    ports:
      - "9087:9087"
    networks:
      - monitor-net
  grafana:
    image: grafana/grafana:8.2.5
    container_name: grafana
    volumes:
      - ./grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - /var/log/grafana:/var/log/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=${ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - GF_SERVER_DOMAIN=${SERVER_DOMAIN}
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_SMTP_ENABLED=${SMTP_ENABLED}
      - GF_SMTP_HOST=${SMTP_HOST}
      - GF_SMTP_USER=${SMTP_USER}
      - GF_SMTP_PASSWORD=${SMTP_PASSWORD}
      - GF_SMTP_SKIP_VERIFY=${SMTP_SKIP_VERIFY}
      - GF_SMTP_FROM_ADDRESS=${SMTP_FROM_ADDRESS}
      - GF_SMTP_FROM_NAME=${SMTP_FROM_NAME}
    user: "991:987"
    restart: unless-stopped
    ports:
      - "3000:3000"
    networks:
      - monitor-net
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    expose:
      - 9090
    networks:
      - monitoring
  alertmanager:
    image: prom/alertmanager:latest
    container_name: alertmanager
    ports:
      - 9093:9093
    volumes:
      - ./alertmanager/:/etc/alertmanager/
    restart: always
    command:
      - '-config.file=/etc/alertmanager/alertmanager.yml'
      - '-storage.path=/alertmanager'
networks:
  monitor-net:
    driver: bridge
