global:
  scrape_interval: 1m
rule_files:
  - './rules.yml'
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - "localhost:9093"
scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 1m
    honor_labels: true
    static_configs:
    - targets: ["localhost:9090"]

  - job_name: "node"
    honor_labels: true
    static_configs:
    - targets: ["172.27.251.111:9100"]

#remote_write:
#  - url: "<Your Prometheus remote_write endpoint>"
#    basic_auth:
#      username: "<Your Grafana Username>"
#      password: "<Your Grafana API key>"
